Update to use dialog or activity depends on devide ERROR contained
DatePickerFragment is used inside CrimeFragment when the device is a tablet or inside of a new Activity named DatePickerActivity when the device is a smartphone.

ERROR: When the device is a smartphone and the user uses the DateButton inside CrimeFragment the app crashes and it causes an error.